import type { TourPackage } from "./packages";
import { packages as packagesEn } from "./packages";

// French copy for each package, keyed by slug. Structural/numeric fields
// (image, price, slug) are reused from the English source so prices and
// currency conversion always stay in sync between locales.
const frText: Record<string, Pick<TourPackage, "name" | "tagline" | "duration" | "priceUnit" | "target" | "hotel" | "transport" | "meals" | "comfort" | "destinations" | "inclusions" | "exclusions" | "itinerary" | "faqs">> = {
  "kartarpur-express": {
    name: "Kartarpur Express",
    tagline: "Un court voyage sacré pour les pèlerins de première visite",
    duration: "3 à 4 jours",
    priceUnit: "/ personne",
    target: "Visiteurs de première fois, courts séjours spirituels, familles",
    hotel: "Hôtels confort 4 étoiles",
    transport: "Véhicules climatisés privés avec chauffeur",
    meals: "Petit-déjeuner quotidien + repas de groupe sélectionnés",
    comfort: "Itinéraire adapté aux personnes âgées, rythme doux",
    destinations: ["Kartarpur Sahib", "Promenade du patrimoine de Lahore", "Frontière de Wagah"],
    inclusions: [
      "Accueil et départ à l'aéroport",
      "Hébergement à l'hôtel (chambre double)",
      "Petit-déjeuner et repas de groupe quotidiens",
      "Transport privé climatisé",
      "Guide agréé du patrimoine sikh (anglais/pendjabi)",
      "Coordination de toutes les visites de gurdwaras",
      "Assistance visa et lettre d'invitation",
    ],
    exclusions: ["Vols internationaux", "Dépenses personnelles", "Assurance voyage", "Frais de visa pakistanais"],
    itinerary: [
      { day: "Jour 1", title: "Arrivée à Lahore", details: "Accueil à l'aéroport, briefing de bienvenue, repos à l'hôtel en soirée." },
      { day: "Jour 2", title: "Darshan à Kartarpur Sahib", details: "Pèlerinage d'une journée complète au Gurdwara Darbar Sahib Kartarpur. Sewa et langar." },
      { day: "Jour 3", title: "Patrimoine sikh de Lahore", details: "Gurdwara Dera Sahib, Samadhi du Maharaja Ranjit Singh, fort de Lahore." },
      { day: "Jour 4", title: "Adieux", details: "Cérémonie optionnelle à la frontière de Wagah, transfert à l'aéroport." },
    ],
    faqs: [
      { q: "Ce circuit convient-il aux voyageurs âgés ?", a: "Oui. Le rythme est doux et tout le transport est privé, avec des dispositions accessibles en fauteuil roulant sur demande." },
      { q: "Gérez-vous le visa pakistanais ?", a: "Nous fournissons une lettre d'invitation complète et un accompagnement étape par étape pour les voyageurs des quatre pays de la diaspora." },
    ],
  },
  "sikh-heritage-of-punjab": {
    name: "Patrimoine Sikh du Pendjab",
    tagline: "Notre circuit phare à travers le Pendjab historique",
    duration: "7 à 10 jours",
    priceUnit: "/ personne",
    target: "Circuit de groupe phare",
    hotel: "Hôtels patrimoniaux 4 et 5 étoiles",
    transport: "Autocars de luxe privés",
    meals: "Pension complète — petit-déjeuner, déjeuner, dîner",
    comfort: "Petits groupes premium de 12 à 18 personnes",
    destinations: ["Nankana Sahib", "Kartarpur Sahib", "Panja Sahib", "Lahore", "Eminabad", "Rohri Sahib"],
    inclusions: [
      "Tout l'hébergement (chambre double)",
      "Pension complète incluant la cuisine pendjabi authentique",
      "Autocar privé de luxe avec chauffeur",
      "Guide historien sikh expert",
      "Tous les permis de site et coordination des gurdwaras",
      "Lettre d'invitation et assistance visa",
      "Eau en bouteille, collations, carte SIM locale",
      "Directeur de voyage disponible 24h/24",
    ],
    exclusions: ["Vols internationaux", "Achats personnels", "Assurance voyage", "Frais de visa pakistanais"],
    itinerary: [
      { day: "Jour 1", title: "Arrivée et accueil à Lahore", details: "Accueil, dîner de bienvenue, briefing." },
      { day: "Jour 2", title: "Nankana Sahib — lieu de naissance de Guru Nanak Dev Ji", details: "Visite du Gurdwara Janam Asthan et des gurdwaras historiques environnants." },
      { day: "Jour 3", title: "Eminabad et Rohri Sahib", details: "Sur les traces des premiers voyages de Guru Nanak." },
      { day: "Jour 4", title: "Panja Sahib (Hasan Abdal)", details: "Empreinte de main sacrée, sarovar, sewa et langar." },
      { day: "Jour 5", title: "Kartarpur Sahib", details: "Journée de recueillement sur le site des dernières années de Guru Nanak." },
      { day: "Jour 6", title: "Patrimoine sikh de Lahore", details: "Gurdwara Dera Sahib, fort de Lahore, samadhi du Maharaja Ranjit Singh." },
      { day: "Jour 7", title: "Ville fortifiée et adieux", details: "Promenade patrimoniale, dîner d'adieu, préparatifs de départ." },
    ],
    faqs: [
      { q: "Quelle est la taille des groupes ?", a: "Petits groupes premium de 12 à 18 personnes. Les délégations de gurdwaras plus importantes sont gérées séparément." },
      { q: "Pouvez-vous accommoder des besoins alimentaires ?", a: "Oui — tous les repas sont végétariens par défaut et nous nous adaptons aux régimes jaïns, sans gluten et adaptés aux seniors." },
    ],
  },
  "roots-and-ancestry-tour": {
    name: "Circuit Racines et Ascendance",
    tagline: "Marchez dans les ruelles que vos grands-parents appelaient chez eux",
    duration: "7 à 14 jours",
    priceUnit: "/ groupe privé",
    target: "Familles à la recherche de villages ancestraux et de racines d'avant la partition",
    hotel: "Hôtels patrimoniaux boutique + 5 étoiles en ville",
    transport: "SUV privés avec chauffeur",
    meals: "Pension complète, style familial",
    comfort: "Entièrement privé, au rythme de la famille",
    destinations: ["Votre village ancestral", "Lahore", "Frontière d'Amritsar", "Étapes historiques personnalisées"],
    inclusions: [
      "Recherche généalogique et cartographie du village avant le voyage",
      "SUV privés avec chauffeur",
      "Hébergement boutique et 5 étoiles",
      "Directeur de voyage familial dédié",
      "Traducteur local et liaison culturelle",
      "Photo et vidéo de style documentaire (en option)",
      "Assistance visa pour toute la famille",
    ],
    exclusions: ["Vols internationaux", "Dépenses personnelles", "Assurance voyage"],
    itinerary: [
      { day: "Jour 1-2", title: "Arrivée et briefing à Lahore", details: "Accueil familial, présentation des recherches généalogiques." },
      { day: "Jour 3-5", title: "Visite du village ancestral", details: "Voyage tranquille vers votre village familial. Rencontre avec les anciens locaux, visite de votre ancienne maison ou terre si elle est retrouvée." },
      { day: "Jour 6-8", title: "Circuit du patrimoine sikh", details: "Nankana Sahib, Panja Sahib, Kartarpur Sahib à votre propre rythme." },
      { day: "Jour 9+", title: "Jours personnalisés", details: "Ajoutez Hasan Abdal, Rawalpindi, Multan, ou plus de temps au village." },
    ],
    faqs: [
      { q: "Comment recherchez-vous le village ancestral ?", a: "À partir du nom de famille, des registres de la partition et de l'histoire orale que vous nous fournissez avant la réservation, notre équipe de recherche cartographie le(s) village(s) probable(s) et confirme avec vous avant le voyage." },
      { q: "Pouvons-nous emmener des membres âgés de la famille ?", a: "Absolument — ce circuit a été conçu pour les familles multigénérationnelles." },
    ],
  },
  "luxury-private-sikh-heritage": {
    name: "Circuit de Luxe Privé du Patrimoine Sikh",
    tagline: "Pèlerinage entièrement sur mesure et haut de gamme",
    duration: "Sur mesure",
    priceUnit: "/ personne",
    target: "Voyageurs privés haut de gamme, familles, invités VIP",
    hotel: "Hôtels 5 étoiles et palaces",
    transport: "Berlines/SUV de luxe privés avec sécurité",
    meals: "Restauration sur mesure, chef privé sur demande",
    comfort: "Entièrement privé, entièrement sur mesure",
    destinations: ["Tous les principaux gurdwaras", "Lahore", "Hasan Abdal", "Sur mesure"],
    inclusions: [
      "Concepteur de voyage personnel",
      "Hébergement 5 étoiles et palace",
      "Véhicules de luxe privés + sécurité",
      "Accès à des historiens privés et granthis lorsque possible",
      "Expériences culinaires sur mesure",
      "Service de conciergerie 24h/24",
      "Service complet de visa et d'aéroport haut de gamme",
    ],
    exclusions: ["Vols internationaux", "Achats personnels"],
    itinerary: [
      { day: "Sur mesure", title: "Conçu autour de vous", details: "Chaque itinéraire est construit individuellement. Exemple : 5 à 14 jours à travers tout le circuit du patrimoine sikh avec des journées de repos et du temps en famille." },
    ],
    faqs: [
      { q: "À quel point est-ce privé ?", a: "Entièrement. Pas de groupes partagés, pas de transport partagé, pas de repas partagés." },
    ],
  },
  "gurdwara-group-pilgrimage": {
    name: "Pèlerinage de Groupe en Gurdwara",
    tagline: "Pour les groupes de sangat de 15 à 40 yatris",
    duration: "7 à 10 jours",
    priceUnit: "/ personne",
    target: "Groupes menés par une gurdwara de 15 à 40 personnes",
    hotel: "Hôtels de groupe 4 étoiles",
    transport: "Autocars de luxe privés",
    meals: "Pension complète avec coordination du langar",
    comfort: "Au rythme du groupe, soutien du jathedar",
    destinations: ["Nankana Sahib", "Kartarpur Sahib", "Panja Sahib", "Lahore", "Eminabad"],
    inclusions: [
      "Tout l'hébergement de groupe",
      "Pension complète et coordination du langar",
      "Autocars de luxe privés",
      "Liaison dédiée avec le jathedar",
      "Tous les permis de site et coordination des gurdwaras",
      "Traitement de visa de groupe",
      "Responsable de groupe sur place 24h/24",
    ],
    exclusions: ["Vols internationaux", "Dépenses personnelles", "Assurance voyage"],
    itinerary: [
      { day: "Jour 1", title: "Arrivée du groupe à Lahore", details: "Accueil en autocar, bienvenue du groupe, dîner de sangat." },
      { day: "Jour 2-3", title: "Nankana Sahib", details: "Deux jours au Janam Asthan et aux gurdwaras historiques voisins." },
      { day: "Jour 4", title: "Panja Sahib", details: "Journée complète de sewa, langar et darshan." },
      { day: "Jour 5-6", title: "Kartarpur Sahib", details: "Deux jours de recueillement, kirtan et sangat." },
      { day: "Jour 7", title: "Patrimoine de Lahore", details: "Gurdwara Dera Sahib, fort de Lahore, samadhi du Maharaja Ranjit Singh." },
      { day: "Jour 8", title: "Départ", details: "Autocar vers l'aéroport, ardas d'adieu." },
    ],
    faqs: [
      { q: "Pouvez-vous gérer le visa du groupe complet ?", a: "Oui — nous traitons régulièrement les visas de groupe pour les délégations de gurdwaras du Royaume-Uni, du Canada, des États-Unis et d'Australie." },
    ],
  },
};

export const packagesFr: TourPackage[] = packagesEn.map((p) => ({
  ...p,
  ...frText[p.slug],
}));

export const findPackageFr = (slug: string) => packagesFr.find((p) => p.slug === slug);
