/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FrRouteImport } from './routes/fr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as FrVisaRouteImport } from './routes/fr/visa'
import { Route as FrToursRouteImport } from './routes/fr/tours'
import { Route as FrTestimonialsRouteImport } from './routes/fr/testimonials'
import { Route as FrTermsRouteImport } from './routes/fr/terms'
import { Route as FrPrivacyRouteImport } from './routes/fr/privacy'
import { Route as FrGalleryRouteImport } from './routes/fr/gallery'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrBlogRouteImport } from './routes/fr/blog'
import { Route as FrAboutRouteImport } from './routes/fr/about'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FrToursSlugRouteImport } from './routes/fr/tours.$slug'
import { Route as FrBlogSlugRouteImport } from './routes/fr/blog.$slug'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrRoute,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const FrVisaRoute = FrVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => FrRoute,
} as any)
const FrToursRoute = FrToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => FrRoute,
} as any)
const FrTestimonialsRoute = FrTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => FrRoute,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FrRoute,
} as any)
const FrPrivacyRoute = FrPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => FrRoute,
} as any)
const FrGalleryRoute = FrGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => FrRoute,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FrRoute,
} as any)
const FrBlogRoute = FrBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => FrRoute,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FrRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const FrToursSlugRoute = FrToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrToursRoute,
} as any)
const FrBlogSlugRoute = FrBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tours': typeof ToursRouteWithChildren
  '/visa': typeof VisaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRouteWithChildren
  '/fr/contact': typeof FrContactRoute
  '/fr/gallery': typeof FrGalleryRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/testimonials': typeof FrTestimonialsRoute
  '/fr/tours': typeof FrToursRouteWithChildren
  '/fr/visa': typeof FrVisaRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/fr/': typeof FrIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/tours/$slug': typeof FrToursSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tours': typeof ToursRouteWithChildren
  '/visa': typeof VisaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRouteWithChildren
  '/fr/contact': typeof FrContactRoute
  '/fr/gallery': typeof FrGalleryRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/testimonials': typeof FrTestimonialsRoute
  '/fr/tours': typeof FrToursRouteWithChildren
  '/fr/visa': typeof FrVisaRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/fr': typeof FrIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/tours/$slug': typeof FrToursSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/fr': typeof FrRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tours': typeof ToursRouteWithChildren
  '/visa': typeof VisaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRouteWithChildren
  '/fr/contact': typeof FrContactRoute
  '/fr/gallery': typeof FrGalleryRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/testimonials': typeof FrTestimonialsRoute
  '/fr/tours': typeof FrToursRouteWithChildren
  '/fr/visa': typeof FrVisaRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/fr/': typeof FrIndexRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/tours/$slug': typeof FrToursSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/fr'
    | '/gallery'
    | '/plan'
    | '/privacy'
    | '/terms'
    | '/testimonials'
    | '/tours'
    | '/visa'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/contact'
    | '/fr/gallery'
    | '/fr/privacy'
    | '/fr/terms'
    | '/fr/testimonials'
    | '/fr/tours'
    | '/fr/visa'
    | '/tours/$slug'
    | '/fr/'
    | '/fr/blog/$slug'
    | '/fr/tours/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/plan'
    | '/privacy'
    | '/terms'
    | '/testimonials'
    | '/tours'
    | '/visa'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/contact'
    | '/fr/gallery'
    | '/fr/privacy'
    | '/fr/terms'
    | '/fr/testimonials'
    | '/fr/tours'
    | '/fr/visa'
    | '/tours/$slug'
    | '/fr'
    | '/fr/blog/$slug'
    | '/fr/tours/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/fr'
    | '/gallery'
    | '/plan'
    | '/privacy'
    | '/terms'
    | '/testimonials'
    | '/tours'
    | '/visa'
    | '/blog/$slug'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/contact'
    | '/fr/gallery'
    | '/fr/privacy'
    | '/fr/terms'
    | '/fr/testimonials'
    | '/fr/tours'
    | '/fr/visa'
    | '/tours/$slug'
    | '/fr/'
    | '/fr/blog/$slug'
    | '/fr/tours/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FrRoute: typeof FrRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ToursRoute: typeof ToursRouteWithChildren
  VisaRoute: typeof VisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/fr/visa': {
      id: '/fr/visa'
      path: '/visa'
      fullPath: '/fr/visa'
      preLoaderRoute: typeof FrVisaRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/tours': {
      id: '/fr/tours'
      path: '/tours'
      fullPath: '/fr/tours'
      preLoaderRoute: typeof FrToursRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/testimonials': {
      id: '/fr/testimonials'
      path: '/testimonials'
      fullPath: '/fr/testimonials'
      preLoaderRoute: typeof FrTestimonialsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/terms': {
      id: '/fr/terms'
      path: '/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/privacy': {
      id: '/fr/privacy'
      path: '/privacy'
      fullPath: '/fr/privacy'
      preLoaderRoute: typeof FrPrivacyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/gallery': {
      id: '/fr/gallery'
      path: '/gallery'
      fullPath: '/fr/gallery'
      preLoaderRoute: typeof FrGalleryRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/blog': {
      id: '/fr/blog'
      path: '/blog'
      fullPath: '/fr/blog'
      preLoaderRoute: typeof FrBlogRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/about': {
      id: '/fr/about'
      path: '/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof FrRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/fr/tours/$slug': {
      id: '/fr/tours/$slug'
      path: '/$slug'
      fullPath: '/fr/tours/$slug'
      preLoaderRoute: typeof FrToursSlugRouteImport
      parentRoute: typeof FrToursRoute
    }
    '/fr/blog/$slug': {
      id: '/fr/blog/$slug'
      path: '/$slug'
      fullPath: '/fr/blog/$slug'
      preLoaderRoute: typeof FrBlogSlugRouteImport
      parentRoute: typeof FrBlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface FrBlogRouteChildren {
  FrBlogSlugRoute: typeof FrBlogSlugRoute
}

const FrBlogRouteChildren: FrBlogRouteChildren = {
  FrBlogSlugRoute: FrBlogSlugRoute,
}

const FrBlogRouteWithChildren =
  FrBlogRoute._addFileChildren(FrBlogRouteChildren)

interface FrToursRouteChildren {
  FrToursSlugRoute: typeof FrToursSlugRoute
}

const FrToursRouteChildren: FrToursRouteChildren = {
  FrToursSlugRoute: FrToursSlugRoute,
}

const FrToursRouteWithChildren =
  FrToursRoute._addFileChildren(FrToursRouteChildren)

interface FrRouteChildren {
  FrAboutRoute: typeof FrAboutRoute
  FrBlogRoute: typeof FrBlogRouteWithChildren
  FrContactRoute: typeof FrContactRoute
  FrGalleryRoute: typeof FrGalleryRoute
  FrPrivacyRoute: typeof FrPrivacyRoute
  FrTermsRoute: typeof FrTermsRoute
  FrTestimonialsRoute: typeof FrTestimonialsRoute
  FrToursRoute: typeof FrToursRouteWithChildren
  FrVisaRoute: typeof FrVisaRoute
  FrIndexRoute: typeof FrIndexRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrAboutRoute: FrAboutRoute,
  FrBlogRoute: FrBlogRouteWithChildren,
  FrContactRoute: FrContactRoute,
  FrGalleryRoute: FrGalleryRoute,
  FrPrivacyRoute: FrPrivacyRoute,
  FrTermsRoute: FrTermsRoute,
  FrTestimonialsRoute: FrTestimonialsRoute,
  FrToursRoute: FrToursRouteWithChildren,
  FrVisaRoute: FrVisaRoute,
  FrIndexRoute: FrIndexRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FrRoute: FrRouteWithChildren,
  GalleryRoute: GalleryRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ToursRoute: ToursRouteWithChildren,
  VisaRoute: VisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
